# Generated by Django 3.1.2 on 2021-07-18 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bug",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, null=True)),
                ("body", models.CharField(max_length=255, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Resolved"), (2, "Unresolved")], default=2
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "bug",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, null=True)),
                ("body", models.CharField(max_length=255, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "bug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="issue.bug",
                    ),
                ),
            ],
            options={
                "db_table": "comment",
                "ordering": ["id"],
            },
        ),
    ]
