# Generated by Django 3.1.2 on 2021-07-18 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bug",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bugs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
